[workspace]
members = ["plait", "plait-macros", "plait-tests"]
resolver = "3"

[workspace.dependencies]
hescape = "0.1.0"
indexmap = "2.13.0"
itoa = "1.0.17"
percent-encoding = "2.3.2"
plait = { path = "./plait" }
plait-macros = { path = "./plait-macros" }
proc-macro2 = "1.0.105"
quote = "1.0.43"
ryu = "1.0.22"
syn = { version = "2.0.114", features = ["full", "extra-traits"] }
thiserror = "2.0.17"
