[package]
name = "plait"
version = "0.4.0"
authors = ["Devashish Dixit <devashishdxt@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A modern HTML templating library for Rust that embraces composition."
homepage = "https://github.com/devashishdxt/plait"
repository = "https://github.com/devashishdxt/plait"
categories = ["template-engine", "web-programming"]
keywords = ["html", "template", "markup"]
edition = "2024"

[dependencies]
hescape.workspace = true
percent-encoding.workspace = true
plait-macros.workspace = true
