[package]
name = "spool-macros"
version = "0.1.0"
description = "Macros for `spool`: A modern HTML templating library for Rust that embraces composition."
edition = "2024"

[lib]
proc-macro = true

[dependencies]
